name: Tests
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: latest

      - name: Install dependencies
        run: yarn

      - name: Smoke test build
        run: yarn build

      - name: Check lint
        run: yarn test:lint

      - name: Check types
        run: yarn test:types

      - name: Run unit tests
        run: yarn test:unit

      - name: Store Playwright's version
        run: |
          PLAYWRIGHT_VERSION=$(yarn list --pattern @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright browsers for current Playwright's version
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright deps
        run: yarn playwright install-deps

      - name: Install Playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: yarn playwright install

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Publish tests resport
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'report-*.xml'
